version: '3'
services:

  php-fpm:
    build:
      context: ./docker/php
    hostname: php-fpm
    container_name: php-fpm
    depends_on:
      - db
    volumes:
      - ./app/public:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
    hostname: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 81:80
    volumes:
      - ./app/public:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  db:
    image: postgres:latest
    restart: always
    hostname: postgresDB
    container_name: postgresDB
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5432

